name: AFK
main: Assassiner354\AFK\Main
api: [3.0.0]
version: 1.0.0
author: Assassiner354
description: §f[§4Note§fLand] §6Einfaches AFK Plugin nutze /afk

commands:
  afk:
    description: AFK command
    permission: afk.cmd

permission:
  afk.cmd:
    default: true
